version: '3.7'
services:
  app:
    build:
      context: "./"
      target: "base"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
volumes:
  bundle:
    driver: local
